// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/zookeeper-txn.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TxnHeader struct {
	ClientId int64 `protobuf:"varint,1,opt,name=clientId" json:"clientId,omitempty"`
	Cxid     int32 `protobuf:"varint,2,opt,name=cxid" json:"cxid,omitempty"`
	Zxid     int64 `protobuf:"varint,3,opt,name=zxid" json:"zxid,omitempty"`
	Time     int64 `protobuf:"varint,4,opt,name=time" json:"time,omitempty"`
	Type     int32 `protobuf:"varint,5,opt,name=type" json:"type,omitempty"`
}

func (m *TxnHeader) Reset()                    { *m = TxnHeader{} }
func (m *TxnHeader) String() string            { return proto.CompactTextString(m) }
func (*TxnHeader) ProtoMessage()               {}
func (*TxnHeader) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *TxnHeader) GetClientId() int64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *TxnHeader) GetCxid() int32 {
	if m != nil {
		return m.Cxid
	}
	return 0
}

func (m *TxnHeader) GetZxid() int64 {
	if m != nil {
		return m.Zxid
	}
	return 0
}

func (m *TxnHeader) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *TxnHeader) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type CreateTxnV0 struct {
	Path      string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Data      []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Acl       []*ACL `protobuf:"bytes,3,rep,name=acl" json:"acl,omitempty"`
	Ephemeral bool   `protobuf:"varint,4,opt,name=ephemeral" json:"ephemeral,omitempty"`
}

func (m *CreateTxnV0) Reset()                    { *m = CreateTxnV0{} }
func (m *CreateTxnV0) String() string            { return proto.CompactTextString(m) }
func (*CreateTxnV0) ProtoMessage()               {}
func (*CreateTxnV0) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *CreateTxnV0) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *CreateTxnV0) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateTxnV0) GetAcl() []*ACL {
	if m != nil {
		return m.Acl
	}
	return nil
}

func (m *CreateTxnV0) GetEphemeral() bool {
	if m != nil {
		return m.Ephemeral
	}
	return false
}

type CreateTxn struct {
	Path           string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Data           []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Acl            []*ACL `protobuf:"bytes,3,rep,name=acl" json:"acl,omitempty"`
	Ephemeral      bool   `protobuf:"varint,4,opt,name=ephemeral" json:"ephemeral,omitempty"`
	ParentCVersion int32  `protobuf:"varint,5,opt,name=parentCVersion" json:"parentCVersion,omitempty"`
}

func (m *CreateTxn) Reset()                    { *m = CreateTxn{} }
func (m *CreateTxn) String() string            { return proto.CompactTextString(m) }
func (*CreateTxn) ProtoMessage()               {}
func (*CreateTxn) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *CreateTxn) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *CreateTxn) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateTxn) GetAcl() []*ACL {
	if m != nil {
		return m.Acl
	}
	return nil
}

func (m *CreateTxn) GetEphemeral() bool {
	if m != nil {
		return m.Ephemeral
	}
	return false
}

func (m *CreateTxn) GetParentCVersion() int32 {
	if m != nil {
		return m.ParentCVersion
	}
	return 0
}

type DeleteTxn struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *DeleteTxn) Reset()                    { *m = DeleteTxn{} }
func (m *DeleteTxn) String() string            { return proto.CompactTextString(m) }
func (*DeleteTxn) ProtoMessage()               {}
func (*DeleteTxn) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *DeleteTxn) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type SetDataTxn struct {
	Path    string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Version int32  `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
}

func (m *SetDataTxn) Reset()                    { *m = SetDataTxn{} }
func (m *SetDataTxn) String() string            { return proto.CompactTextString(m) }
func (*SetDataTxn) ProtoMessage()               {}
func (*SetDataTxn) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *SetDataTxn) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SetDataTxn) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SetDataTxn) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type CheckVersionTxn struct {
	Path    string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Version int32  `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (m *CheckVersionTxn) Reset()                    { *m = CheckVersionTxn{} }
func (m *CheckVersionTxn) String() string            { return proto.CompactTextString(m) }
func (*CheckVersionTxn) ProtoMessage()               {}
func (*CheckVersionTxn) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *CheckVersionTxn) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *CheckVersionTxn) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type SetACLTxn struct {
	Path    string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Acl     []*ACL `protobuf:"bytes,2,rep,name=acl" json:"acl,omitempty"`
	Version int32  `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
}

func (m *SetACLTxn) Reset()                    { *m = SetACLTxn{} }
func (m *SetACLTxn) String() string            { return proto.CompactTextString(m) }
func (*SetACLTxn) ProtoMessage()               {}
func (*SetACLTxn) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *SetACLTxn) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SetACLTxn) GetAcl() []*ACL {
	if m != nil {
		return m.Acl
	}
	return nil
}

func (m *SetACLTxn) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type SetMaxChildrenTxn struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Max  int32  `protobuf:"varint,2,opt,name=max" json:"max,omitempty"`
}

func (m *SetMaxChildrenTxn) Reset()                    { *m = SetMaxChildrenTxn{} }
func (m *SetMaxChildrenTxn) String() string            { return proto.CompactTextString(m) }
func (*SetMaxChildrenTxn) ProtoMessage()               {}
func (*SetMaxChildrenTxn) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *SetMaxChildrenTxn) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SetMaxChildrenTxn) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

type CreateSessionTxn struct {
	TimeOut int32 `protobuf:"varint,1,opt,name=timeOut" json:"timeOut,omitempty"`
}

func (m *CreateSessionTxn) Reset()                    { *m = CreateSessionTxn{} }
func (m *CreateSessionTxn) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionTxn) ProtoMessage()               {}
func (*CreateSessionTxn) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *CreateSessionTxn) GetTimeOut() int32 {
	if m != nil {
		return m.TimeOut
	}
	return 0
}

type ErrorTxn struct {
	Err int32 `protobuf:"varint,1,opt,name=err" json:"err,omitempty"`
}

func (m *ErrorTxn) Reset()                    { *m = ErrorTxn{} }
func (m *ErrorTxn) String() string            { return proto.CompactTextString(m) }
func (*ErrorTxn) ProtoMessage()               {}
func (*ErrorTxn) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

func (m *ErrorTxn) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

type Txn struct {
	Type int32  `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Txn) Reset()                    { *m = Txn{} }
func (m *Txn) String() string            { return proto.CompactTextString(m) }
func (*Txn) ProtoMessage()               {}
func (*Txn) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{10} }

func (m *Txn) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Txn) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type MultiTxn struct {
	Txns []*Txn `protobuf:"bytes,1,rep,name=txns" json:"txns,omitempty"`
}

func (m *MultiTxn) Reset()                    { *m = MultiTxn{} }
func (m *MultiTxn) String() string            { return proto.CompactTextString(m) }
func (*MultiTxn) ProtoMessage()               {}
func (*MultiTxn) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{11} }

func (m *MultiTxn) GetTxns() []*Txn {
	if m != nil {
		return m.Txns
	}
	return nil
}

func init() {
	proto.RegisterType((*TxnHeader)(nil), "model.TxnHeader")
	proto.RegisterType((*CreateTxnV0)(nil), "model.CreateTxnV0")
	proto.RegisterType((*CreateTxn)(nil), "model.CreateTxn")
	proto.RegisterType((*DeleteTxn)(nil), "model.DeleteTxn")
	proto.RegisterType((*SetDataTxn)(nil), "model.SetDataTxn")
	proto.RegisterType((*CheckVersionTxn)(nil), "model.CheckVersionTxn")
	proto.RegisterType((*SetACLTxn)(nil), "model.SetACLTxn")
	proto.RegisterType((*SetMaxChildrenTxn)(nil), "model.SetMaxChildrenTxn")
	proto.RegisterType((*CreateSessionTxn)(nil), "model.CreateSessionTxn")
	proto.RegisterType((*ErrorTxn)(nil), "model.ErrorTxn")
	proto.RegisterType((*Txn)(nil), "model.Txn")
	proto.RegisterType((*MultiTxn)(nil), "model.MultiTxn")
}

func init() { proto.RegisterFile("model/zookeeper-txn.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0xb3, 0x31, 0xb5, 0xa7, 0x08, 0x82, 0x4f, 0x4b, 0x14, 0x41, 0xb4, 0x07, 0x14, 0x21,
	0x1a, 0x10, 0x9c, 0x38, 0xa1, 0xca, 0x45, 0x02, 0xa9, 0x05, 0x69, 0x1d, 0x95, 0xf3, 0x62, 0x8f,
	0x64, 0xab, 0xf6, 0xda, 0x6c, 0xb6, 0xb0, 0xf4, 0x47, 0xf8, 0x5d, 0xb4, 0x63, 0xa7, 0xa5, 0x55,
	0x7c, 0xe0, 0xd2, 0xdb, 0xdb, 0x97, 0x37, 0xf3, 0xde, 0x4c, 0xc6, 0xf0, 0xb4, 0x69, 0x0b, 0xac,
	0x5f, 0x5f, 0xb5, 0xed, 0x05, 0x62, 0x87, 0xe6, 0xc8, 0x3a, 0xbd, 0xee, 0x4c, 0x6b, 0xdb, 0x24,
	0xa4, 0x9f, 0xe6, 0xf3, 0xbb, 0x8a, 0x42, 0x59, 0xd5, 0x4b, 0xc4, 0x2f, 0x88, 0x37, 0x4e, 0x7f,
	0x42, 0x55, 0xa0, 0x49, 0xe6, 0x10, 0xe5, 0x75, 0x85, 0xda, 0x7e, 0x2e, 0x78, 0xb0, 0x0c, 0x56,
	0x4c, 0x5e, 0xbf, 0x93, 0x04, 0xa6, 0xb9, 0xab, 0x0a, 0x3e, 0x59, 0x06, 0xab, 0x50, 0x12, 0xf6,
	0xdc, 0x95, 0xe7, 0x18, 0x69, 0x09, 0x7b, 0xce, 0x56, 0x0d, 0xf2, 0x69, 0xcf, 0x79, 0x4c, 0xdc,
	0xef, 0x0e, 0x79, 0xd8, 0xd7, 0x7a, 0x2c, 0x7e, 0xc0, 0x61, 0x6a, 0x50, 0x59, 0xdc, 0x38, 0x7d,
	0xfe, 0xc6, 0x4b, 0x3a, 0x65, 0x4b, 0xb2, 0x8d, 0x25, 0x61, 0xcf, 0xf9, 0xa4, 0x64, 0xf9, 0x50,
	0x12, 0x4e, 0x16, 0xc0, 0x54, 0x5e, 0x73, 0xb6, 0x64, 0xab, 0xc3, 0xb7, 0xb0, 0xa6, 0xc9, 0xd6,
	0xc7, 0xe9, 0xa9, 0xf4, 0x74, 0xb2, 0x80, 0x18, 0xbb, 0x12, 0x1b, 0x34, 0xaa, 0xa6, 0x04, 0x91,
	0xbc, 0x21, 0xc4, 0x9f, 0x00, 0xe2, 0x6b, 0xcf, 0xfb, 0x70, 0x4c, 0x5e, 0xc0, 0xa3, 0x4e, 0x19,
	0xd4, 0x36, 0x3d, 0x47, 0xb3, 0xad, 0x5a, 0x3d, 0xac, 0xe0, 0x0e, 0x2b, 0x9e, 0x43, 0x7c, 0x82,
	0x35, 0x8e, 0x06, 0x13, 0x5f, 0x00, 0x32, 0xb4, 0x27, 0xca, 0xaa, 0xff, 0x89, 0xce, 0xe1, 0xe0,
	0xe7, 0xe0, 0xcb, 0xc8, 0x77, 0xf7, 0x14, 0x1f, 0xe0, 0x71, 0x5a, 0x62, 0x7e, 0x31, 0x04, 0x18,
	0x6b, 0xfa, 0x4f, 0x83, 0xc9, 0xed, 0x06, 0xdf, 0x20, 0xce, 0xd0, 0x1e, 0xa7, 0xa7, 0x63, 0xa5,
	0xc3, 0xda, 0x26, 0xfb, 0xd7, 0x36, 0x9e, 0xec, 0x3d, 0x3c, 0xc9, 0xd0, 0x9e, 0x29, 0x97, 0x96,
	0x55, 0x5d, 0x18, 0x1c, 0xcd, 0x36, 0x03, 0xd6, 0x28, 0x37, 0xe4, 0xf2, 0x50, 0xbc, 0x82, 0x59,
	0xff, 0xf7, 0x66, 0xb8, 0xdd, 0x4d, 0xc5, 0xe1, 0xc0, 0x9f, 0xe0, 0xd7, 0x4b, 0x4b, 0xc5, 0xa1,
	0xdc, 0x3d, 0xc5, 0x02, 0xa2, 0x8f, 0xc6, 0xb4, 0xc6, 0xab, 0x66, 0xc0, 0xd0, 0x98, 0x41, 0xe1,
	0xa1, 0x38, 0x02, 0x36, 0x18, 0xd3, 0xe5, 0x06, 0x37, 0x97, 0xbb, 0x6f, 0xd3, 0xe2, 0x25, 0x44,
	0x67, 0x97, 0xb5, 0xad, 0x7c, 0xcd, 0x33, 0x98, 0x5a, 0xa7, 0xb7, 0x3c, 0xb8, 0x35, 0xfa, 0xc6,
	0x69, 0x49, 0xfc, 0xf7, 0x07, 0xf4, 0xe5, 0xbd, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xb3,
	0x18, 0x7b, 0xb9, 0x03, 0x00, 0x00,
}
